//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportSystemSrdjan.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main
    {
        public int ID { get; set; }
        public Nullable<int> SugestionNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> AcceptedOn { get; set; }
        public Nullable<System.DateTime> DueOn { get; set; }
        public string ResolvedOn { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public string Steps { get; set; }
        public string Notes { get; set; }
        public Nullable<int> SectionID { get; set; }
        public string StepsToReproduce { get; set; }
        public string Title { get; set; }
        public Nullable<int> SeverityID { get; set; }
        public Nullable<int> CommentID { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual SupportSystemCategory SupportSystemCategory { get; set; }
        public virtual SupportSystemPriority SupportSystemPriority { get; set; }
        public virtual SupportSystemSection SupportSystemSection { get; set; }
        public virtual SupportSystemSeverity SupportSystemSeverity { get; set; }
        public virtual SupportSystemStatu SupportSystemStatu { get; set; }
    }
}
