//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportSystemSrdjan.DBModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SupportSystemSrdjanContext : DbContext
    {
        public SupportSystemSrdjanContext()
            : base("name=SupportSystemSrdjanContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Main> Mains { get; set; }
        public virtual DbSet<SupportSystemCategory> SupportSystemCategories { get; set; }
        public virtual DbSet<SupportSystemPriority> SupportSystemPriorities { get; set; }
        public virtual DbSet<SupportSystemRole> SupportSystemRoles { get; set; }
        public virtual DbSet<SupportSystemSection> SupportSystemSections { get; set; }
        public virtual DbSet<SupportSystemSeverity> SupportSystemSeverities { get; set; }
        public virtual DbSet<SupportSystemStatu> SupportSystemStatus { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
